package model;
// Generated 14/05/2015 12:02:46 by Hibernate Tools 4.3.1

import dao.AlunoDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aluno generated by hbm2java
 */
@Entity
@Table(name = "aluno", catalog = "scp"
)
public class Aluno implements java.io.Serializable {

    private int idAluno;
    private Curso curso;
    private Projeto projeto;
    private String nome;
    private String identidade;
    private String cpf;
    private String nascimento;
    private String matricula;
    private String naturalidade;
    private String nacionalidade;
    private String estado;
    private String cidade;
    private String cep;
    private String rua;
    private String numero;
    private String complemento;
    private String bairro;
    private String telefoneResidencial;
    private String celular;
    private String email;
    private String situacaoMilitar;
    private String certidaoMilitar;
    private String localTrabalho;
    private String telefoneTrabalho;
    private String banco;
    private String agencia;
    private String contaCorrente;
    

    public Aluno() {
    }

    public Aluno(int idAluno, Curso curso, String nome, String identidade, String cpf, String nascimento, String matricula, String naturalidade, String nacionalidade, String estado, String cidade, String cep, String rua, String numero, String complemento, String bairro, String telefoneResidencial, String celular, String email, String situacaoMilitar, String certidaoMilitar, String localTrabalho, String telefoneTrabalho, String banco, String agencia, String contaCorrente) {
        this.idAluno = idAluno;
        this.curso = curso;
        this.nome = nome;
        this.identidade = identidade;
        this.cpf = cpf;
        this.nascimento = nascimento;
        this.matricula = matricula;
        this.naturalidade = naturalidade;
        this.nacionalidade = nacionalidade;
        this.estado = estado;
        this.cidade = cidade;
        this.cep = cep;
        this.rua = rua;
        this.numero = numero;
        this.complemento = complemento;
        this.bairro = bairro;
        this.telefoneResidencial = telefoneResidencial;
        this.celular = celular;
        this.email = email;
        this.situacaoMilitar = situacaoMilitar;
        this.certidaoMilitar = certidaoMilitar;
        this.localTrabalho = localTrabalho;
        this.telefoneTrabalho = telefoneTrabalho;
        this.banco = banco;
        this.agencia = agencia;
        this.contaCorrente = contaCorrente;
    }

    
    
    public Aluno(int idAluno, String nome, String identidade, String cpf, String nascimento, String matricula, String naturalidade, String nacionalidade, String estado, String cidade, String cep, String rua, String numero, String complemento, String bairro, String telefoneResidencial, String celular, String email, String situacaoMilitar, String certidaoMilitar, String localTrabalho, String telefoneTrabalho, String banco, String agencia, String contaCorrente) {
        this.idAluno = idAluno;
        this.nome = nome;
        this.identidade = identidade;
        this.cpf = cpf;
        this.nascimento = nascimento;
        this.matricula = matricula;
        this.naturalidade = naturalidade;
        this.nacionalidade = nacionalidade;
        this.estado = estado;
        this.cidade = cidade;
        this.cep = cep;
        this.rua = rua;
        this.numero = numero;
        this.complemento = complemento;
        this.bairro = bairro;
        this.telefoneResidencial = telefoneResidencial;
        this.celular = celular;
        this.email = email;
        this.situacaoMilitar = situacaoMilitar;
        this.certidaoMilitar = certidaoMilitar;
        this.localTrabalho = localTrabalho;
        this.telefoneTrabalho = telefoneTrabalho;
        this.banco = banco;
        this.agencia = agencia;
        this.contaCorrente = contaCorrente;
    }


    @Id

    @Column(name = "idAluno", unique = true, nullable = false)
    public int getIdAluno() {
        return this.idAluno;
    }

    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idCurso")
    public Curso getCurso() {
        return this.curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name = "nome", nullable = false, length = 128)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "identidade", nullable = false, length = 128)
    public String getIdentidade() {
        return this.identidade;
    }

    public void setIdentidade(String identidade) {
        this.identidade = identidade;
    }

    @Column(name = "cpf", nullable = false, length = 128)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "nascimento", nullable = false, length = 128)
    public String getNascimento() {
        return this.nascimento;
    }

    public void setNascimento(String nascimento) {
        this.nascimento = nascimento;
    }

    @Column(name = "matricula", nullable = false, length = 128)
    public String getMatricula() {
        return this.matricula;
    }

    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    @Column(name = "naturalidade", nullable = false, length = 128)
    public String getNaturalidade() {
        return this.naturalidade;
    }

    public void setNaturalidade(String naturalidade) {
        this.naturalidade = naturalidade;
    }

    @Column(name = "nacionalidade", nullable = false, length = 128)
    public String getNacionalidade() {
        return this.nacionalidade;
    }

    public void setNacionalidade(String nacionalidade) {
        this.nacionalidade = nacionalidade;
    }

    @Column(name = "estado", nullable = false, length = 128)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "cidade", nullable = false, length = 128)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    @Column(name = "cep", nullable = false, length = 128)
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Column(name = "rua", nullable = false, length = 128)
    public String getRua() {
        return this.rua;
    }

    public void setRua(String rua) {
        this.rua = rua;
    }

    @Column(name = "numero", nullable = false, length = 128)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "complemento", nullable = false, length = 128)
    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    @Column(name = "bairro", nullable = false, length = 128)
    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    @Column(name = "telefoneResidencial", nullable = false, length = 128)
    public String getTelefoneResidencial() {
        return this.telefoneResidencial;
    }

    public void setTelefoneResidencial(String telefoneResidencial) {
        this.telefoneResidencial = telefoneResidencial;
    }

    @Column(name = "celular", nullable = false, length = 128)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name = "email", nullable = false, length = 128)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "situacaoMilitar", nullable = false, length = 128)
    public String getSituacaoMilitar() {
        return this.situacaoMilitar;
    }

    public void setSituacaoMilitar(String situacaoMilitar) {
        this.situacaoMilitar = situacaoMilitar;
    }

    @Column(name = "certidaoMilitar", nullable = false, length = 128)
    public String getCertidaoMilitar() {
        return this.certidaoMilitar;
    }

    public void setCertidaoMilitar(String certidaoMilitar) {
        this.certidaoMilitar = certidaoMilitar;
    }

    @Column(name = "localTrabalho", nullable = false, length = 128)
    public String getLocalTrabalho() {
        return this.localTrabalho;
    }

    public void setLocalTrabalho(String localTrabalho) {
        this.localTrabalho = localTrabalho;
    }

    @Column(name = "telefoneTrabalho", nullable = false, length = 128)
    public String getTelefoneTrabalho() {
        return this.telefoneTrabalho;
    }

    public void setTelefoneTrabalho(String telefoneTrabalho) {
        this.telefoneTrabalho = telefoneTrabalho;
    }

    @Column(name = "banco", nullable = false, length = 128)
    public String getBanco() {
        return this.banco;
    }

    public void setBanco(String banco) {
        this.banco = banco;
    }

    @Column(name = "agencia", nullable = false, length = 128)
    public String getAgencia() {
        return this.agencia;
    }

    public void setAgencia(String agencia) {
        this.agencia = agencia;
    }

    @Column(name = "contaCorrente", nullable = false, length = 128)
    public String getContaCorrente() {
        return this.contaCorrente;
    }

    public void setContaCorrente(String contaCorrente) {
        this.contaCorrente = contaCorrente;
    }

    public static List<Aluno> obterAlunos() throws ClassNotFoundException, SQLException {
        return AlunoDAO.obterAlunos();
    }

    public static Aluno obterAluno(int idAluno) throws ClassNotFoundException, SQLException {
        return AlunoDAO.obterAluno(idAluno);
    }

    public static List<Aluno> obterAlunoProNome(String nome) throws ClassNotFoundException,
            SQLException {
        return AlunoDAO.obterAlunosPorNome(nome);
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        AlunoDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        AlunoDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
       AlunoDAO.excluir(this);
    }
   
    
}
