package model;
// Generated 14/05/2015 12:02:46 by Hibernate Tools 4.3.1

import dao.CursoDAO;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", catalog = "scp"
)
public class Curso implements java.io.Serializable {

    private int idCurso;
    private String nome;

    public Curso() {
    }

    public Curso(int idCurso, String nome) {
        this.idCurso = idCurso;
        this.nome = nome;
    }


    @Id

    @Column(name = "idCurso", unique = true, nullable = false)
    public int getIdCurso() {
        return this.idCurso;
    }

    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }

    @Column(name = "nome", nullable = false, length = 45)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }


    public static List<Curso> obterCursos() throws ClassNotFoundException, SQLException {
        return CursoDAO.obterCursos();
    }

    public static Curso obterCurso(int idCurso) throws ClassNotFoundException, SQLException {
        return CursoDAO.obterCurso(idCurso);
    }

    public static List<Curso> obterCursoProNome(String nome) throws ClassNotFoundException,
            SQLException {
        return CursoDAO.obterCursosPorNome(nome);
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        CursoDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        CursoDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        CursoDAO.excluir(this);
    }

}
