package model;
// Generated 14/05/2015 12:02:46 by Hibernate Tools 4.3.1

import dao.EditalDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edital generated by hbm2java
 */
@Entity
@Table(name = "edital", catalog = "scp"
)
public class Edital implements java.io.Serializable {

    private int idEdital;
    private Diretoria diretoria;
    private int numero;
    private String inicio;
    private String fim;
    private String descricao;

    public Edital() {
    }

    public Edital(int idEdital, Diretoria diretoria, int numero, String inicio, String fim, String descricao) {
        this.idEdital = idEdital;
        this.diretoria = diretoria;
        this.numero = numero;
        this.inicio = inicio;
        this.fim = fim;
        this.descricao = descricao;
    }  

    @Id

    @Column(name = "idEdital", unique = true, nullable = false)
    public int getIdEdital() {
        return this.idEdital;
    }

    public void setIdEdital(int idEdital) {
        this.idEdital = idEdital;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idDiretoria", nullable = false)
    public Diretoria getDiretoria() {
        return this.diretoria;
    }

    public void setDiretoria(Diretoria diretoria) {
        this.diretoria = diretoria;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @Column(name = "inicio", nullable = false)
    public String getInicio() {
        return this.inicio;
    }

    public void setInicio(String inicio) {
        this.inicio = inicio;
    }

    @Column(name = "fim", nullable = false)
    public String getFim() {
        return this.fim;
    }

    public void setFim(String fim) {
        this.fim = fim;
    }

    @Column(name = "descricao", nullable = false, length = 1024)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


    public static List<Edital> obterEditais() throws ClassNotFoundException, SQLException {
        return EditalDAO.obterEditais();
    }

    public static Edital obterEdital(int idEdital) throws ClassNotFoundException, SQLException {
        return EditalDAO.obterEdital(idEdital);
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        EditalDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        EditalDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        EditalDAO.excluir(this);
    }

}
