package model;
// Generated 14/05/2015 12:02:46 by Hibernate Tools 4.3.1

import dao.ProfessorDAO;
import java.sql.SQLException;
import java.util.List;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professor generated by hbm2java
 */
@Entity
@Table(name = "professor", catalog = "scp"
)
public class Professor implements java.io.Serializable {

    private int idProfessor;
    private String siape;
    private String nome;
    private String cpf;
    private String dataNascimento;
    private String nacionalide;
    private String email;
    private String homePage;
    private String campus;
    private String telefoneResidencial;
    private String celular;
    private String cidade;


    public Professor() {
    }

    public Professor(int idProfessor, String siape, String nome, String cpf, String dataNascimento, String nacionalide, String email, String homePage, String campus, String telefoneResidencial, String celular, String cidade) {
        this.idProfessor = idProfessor;
        this.siape = siape;
        this.nome = nome;
        this.cpf = cpf;
        this.dataNascimento = dataNascimento;
        this.nacionalide = nacionalide;
        this.email = email;
        this.homePage = homePage;
        this.campus = campus;
        this.telefoneResidencial = telefoneResidencial;
        this.celular = celular;
        this.cidade = cidade;
    }


    @Id

    @Column(name = "idProfessor", unique = true, nullable = false)
    public int getIdProfessor() {
        return this.idProfessor;
    }

    public void setIdProfessor(int idProfessor) {
        this.idProfessor = idProfessor;
    }

    @Column(name = "siape", nullable = false, length = 128)
    public String getSiape() {
        return this.siape;
    }

    public void setSiape(String siape) {
        this.siape = siape;
    }

    @Column(name = "Nome", nullable = false, length = 128)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "CPF", nullable = false, length = 128)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "Data_Nascimento", nullable = false, length = 128)
    public String getDataNascimento() {
        return this.dataNascimento;
    }

    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @Column(name = "Nacionalide", nullable = false, length = 128)
    public String getNacionalide() {
        return this.nacionalide;
    }

    public void setNacionalide(String nacionalide) {
        this.nacionalide = nacionalide;
    }

    @Column(name = "Email", nullable = false, length = 128)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "HomePage", nullable = false, length = 128)
    public String getHomePage() {
        return this.homePage;
    }

    public void setHomePage(String homePage) {
        this.homePage = homePage;
    }

    @Column(name = "Campus", nullable = false, length = 128)
    public String getCampus() {
        return this.campus;
    }

    public void setCampus(String campus) {
        this.campus = campus;
    }

    @Column(name = "Telefone_Residencial", nullable = false, length = 128)
    public String getTelefoneResidencial() {
        return this.telefoneResidencial;
    }

    public void setTelefoneResidencial(String telefoneResidencial) {
        this.telefoneResidencial = telefoneResidencial;
    }

    @Column(name = "Celular", nullable = false, length = 128)
    public String getCelular() {
        return this.celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    @Column(name = "Cidade", nullable = false, length = 128)
    public String getCidade() {
        return this.cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }


    public static List<Professor> obterProfessores() throws ClassNotFoundException, SQLException {
        return ProfessorDAO.obterProfessores();
    }

    public static Professor obterProfessor(int idProfessor) throws ClassNotFoundException, SQLException {
        return ProfessorDAO.obterProfessor(idProfessor);
    }

    public static List<Professor> obterProfessorProNome(String nome) throws ClassNotFoundException,
            SQLException {
        return ProfessorDAO.obterProfessoresPorNome(nome);
    }

    public void gravar() throws SQLException, ClassNotFoundException {
        ProfessorDAO.gravar(this);
    }

    public void editar() throws SQLException, ClassNotFoundException {
        ProfessorDAO.editar(this);
    }

    public void excluir() throws SQLException, ClassNotFoundException {
        ProfessorDAO.excluir(this);
    }
    
}
